export type NoteType = {
  aging?: number | null;
  alc?: number | null;
  bottled?: number | null;
  bottler?: string;
  comment?: string;
  date?: Date;
  distillery_name?: string;
  docId?: string;
  finish?: string;
  image_path?: string;
  images?: Array<string>;
  nose?: string;
  rating?: number | null;
  region?: string;
  taste?: string;
  type?: string;
  uid: string;
  vintage?: number | null;
};
